version: "3.8"

services:
  rtmp-middleware:
    build: .
    ports:
      - "${RTMP_HOST_PORT:-1935}:1935" # RTMP ingest (configurable)
      - "3343:3000" # Next.js web app (host 3343 -> container 3000)
      - "8343:8080" # API server (host 8343 -> container 8080)
      - "${NGINX_PORT:-8081}:80" # Nginx HTTP (configurable; defaults to 8081)
    volumes:
      - ./streams:/tmp/streams
      - ./logs:/var/log/nginx
      - ./config:/app/config
    environment:
      - NODE_ENV=production
      - RTMP_PORT=1935
      - API_PORT=8080
      - WEB_PORT=3000
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
